Update patch set 2
Patch Set 2:

> Patch Set 2: Code-Review-2
> 
> ERROR: /home/jagrav/potato/frameworks/base/services/core/java/com/android/server/policy/PhoneWindowManager.java:6269.57: SOURCE_NAVIGATION_BAR cannot be resolved or is not a field

This requires 
https://review.potatoproject.co/c/PotatoProject/frameworks_base/+/156

Patch-set: 2
Reviewer: Shreyansh Lodha <1000002@8720d348-3d66-43e6-b480-1d69039ac554>